### ISSUE TITLE
Defy update? 

### ISSUE THREAD

**Issue by unsivilaudio** [scala-network/cryptonote-nodejs-pool#20]
Any chance this can easily be updated to the new algorithm "defyX"? I've already started muddling through the pool.js but I understand very little of how the hashing module works. So I am still getting bad shares.

**Comment by ahmyi** [comment]
@unsivilaudio try looking at https://github.com/scala-network/xla-nodejs-pool/blob/v1.4.0_scala/lib/pool.js for heads up.

**Comment by ahmyi** [comment]
Oh ya the config.json

`
  "cnAlgorithm": "randomx",
  "cnVariant": 4,
  "cnBlobType": 10,

`

**Comment by unsivilaudio** [comment]
Well something is still off with your code, the [hashing module](https://github.com/scala-network/scala-hashing) doesn't like your convertedBlob.

"Exception: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object."

**Comment by ahmyi** [comment]
Have you try using node v11 (11.9) can you show the error log file

**Comment by unsivilaudio** [comment]
Node v11.9, clean pull of the 1.4.0 branch
http://prntscr.com/ovpl32
